Repository elastic/elastic-transport-js, pull requests merged in 2022-02, with the labels that each got.

#37 Update Accept header handling
  src/Transport.ts
Labels: backport 8.0, backport 8.1

#42 Cleanup abort listener
  src/connection/HttpConnection.ts
  test/unit/http-connection.test.ts
Labels: bug, backport 8.0, backport 8.1

#41 perf: minor undici tuning
  package.json
  src/connection/UndiciConnection.ts
  test/acceptance/events-order.test.ts
Labels: enhancement, backport 8.0, backport 8.1
